name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install cfssl
        run: go install github.com/cloudflare/cfssl/cmd/...@latest
      - name: Run make init
        run: make init
      - name: Run make gencert
        run: make gencert
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
